import type { DealFields } from "./types";

export const DEMO_TRANSACTION: DealFields = {
  address: "604 2nd St NW",
  city: "Gordo",
  state: "AL",
  zip: "35466",
  county: "Pickens",
  listPrice: 208000,
  salePrice: 208000,
  sellers: ["Amy Rohrer", "Larry K. Chung", "Xuan Vuong"],
  buyers: ["Shaina Fields", "Kevin Fields"],
  listingAgent: "Jerrod Hastings",
  brokerage: "Pritchett-Moore Real Estate",
  buyerAgent: "Damon Gann",
  buyerBrokerage: "KW Tuscaloosa",
  listingDate: "2025-11-16",
  closingDate: "2026-06-05",
  propertyType: "Single-family residential",
  bedBath: null,
  sqft: null,
  yearBuilt: null,
  mlsNumber: null,
  parcelId: "54110209300019002",
  subdivision: "Ridge Sub",
  loanType: "FHA",
  earnestMoney: 1000,
  sellerConcessions: 9700,
  appurtenances: ["refrigerator", "washer", "dryer"],
  flags: {
    leadPaintDisclosure: true,
    recadRequired: true,
    buyerBeware: true,
    relocationCompany: false,
    fhaLoan: true,
    loanTypeChanged: true,
  },
};
